version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "${PORT}:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nette_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d nette_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s