<?php declare(strict_types=1);

namespace App\UI\Home;

use App\Model\Db\Entity\User;
use App\Model\Db\Repository\UserRepository;
use Nette;
use Nette\DI\Attributes\Inject;

final class HomePresenter extends Nette\Application\UI\Presenter
{
    #[Inject]
    public UserRepository $userRepository;

    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        $x = new User();
        $x->username = "x";
        $x->password = "x";
        $x->email = "x";
        $this->userRepository->attach($x);
        $this->userRepository->persistAndFlush($x);
    }
}
