INSERT INTO country (id, name, continent, flag_emoji) VALUES
    -- Europe
    ('CZ', 'Czech Republic',   'Europe',        '🇨🇿'),
    ('SK', 'Slovakia',         'Europe',        '🇸🇰'),
    ('AT', 'Austria',          'Europe',        '🇦🇹'),
    ('DE', 'Germany',          'Europe',        '🇩🇪'),
    ('FR', 'France',           'Europe',        '🇫🇷'),
    ('IT', 'Italy',            'Europe',        '🇮🇹'),
    ('ES', 'Spain',            'Europe',        '🇪🇸'),
    ('PT', 'Portugal',         'Europe',        '🇵🇹'),
    ('NL', 'Netherlands',      'Europe',        '🇳🇱'),
    ('BE', 'Belgium',          'Europe',        '🇧🇪'),
    ('CH', 'Switzerland',      'Europe',        '🇨🇭'),
    ('PL', 'Poland',           'Europe',        '🇵🇱'),
    ('HR', 'Croatia',          'Europe',        '🇭🇷'),
    ('GR', 'Greece',           'Europe',        '🇬🇷'),
    ('GB', 'United Kingdom',   'Europe',        '🇬🇧'),
    ('NO', 'Norway',           'Europe',        '🇳🇴'),
    ('SE', 'Sweden',           'Europe',        '🇸🇪'),
    ('FI', 'Finland',          'Europe',        '🇫🇮'),
    ('DK', 'Denmark',          'Europe',        '🇩🇰'),
    ('IE', 'Ireland',          'Europe',        '🇮🇪'),
    ('HU', 'Hungary',          'Europe',        '🇭🇺'),
    ('RO', 'Romania',          'Europe',        '🇷🇴'),
    ('BG', 'Bulgaria',         'Europe',        '🇧🇬'),
    ('SI', 'Slovenia',         'Europe',        '🇸🇮'),
    ('RS', 'Serbia',           'Europe',        '🇷🇸'),
    ('UA', 'Ukraine',          'Europe',        '🇺🇦'),
    ('LT', 'Lithuania',        'Europe',        '🇱🇹'),
    ('LV', 'Latvia',           'Europe',        '🇱🇻'),
    ('EE', 'Estonia',          'Europe',        '🇪🇪'),

    -- North America
    ('US', 'United States',    'North America', '🇺🇸'),
    ('CA', 'Canada',           'North America', '🇨🇦'),
    ('MX', 'Mexico',           'North America', '🇲🇽'),
    ('CU', 'Cuba',             'North America', '🇨🇺'),
    ('DO', 'Dominican Republic','North America','🇩🇴'),
    ('JM', 'Jamaica',          'North America', '🇯🇲'),

    -- South America
    ('BR', 'Brazil',           'South America', '🇧🇷'),
    ('AR', 'Argentina',        'South America', '🇦🇷'),
    ('CL', 'Chile',            'South America', '🇨🇱'),
    ('CO', 'Colombia',         'South America', '🇨🇴'),
    ('PE', 'Peru',             'South America', '🇵🇪'),
    ('VE', 'Venezuela',        'South America', '🇻🇪'),
    ('UY', 'Uruguay',          'South America', '🇺🇾'),
    ('PY', 'Paraguay',         'South America', '🇵🇾'),

    -- Asia
    ('JP', 'Japan',            'Asia',          '🇯🇵'),
    ('CN', 'China',            'Asia',          '🇨🇳'),
    ('KR', 'South Korea',      'Asia',          '🇰🇷'),
    ('KP', 'North Korea',      'Asia',          '🇰🇵'),
    ('TH', 'Thailand',         'Asia',          '🇹🇭'),
    ('VN', 'Vietnam',          'Asia',          '🇻🇳'),
    ('ID', 'Indonesia',        'Asia',          '🇮🇩'),
    ('MY', 'Malaysia',         'Asia',          '🇲🇾'),
    ('SG', 'Singapore',        'Asia',          '🇸🇬'),
    ('PH', 'Philippines',      'Asia',          '🇵🇭'),
    ('IN', 'India',            'Asia',          '🇮🇳'),
    ('PK', 'Pakistan',         'Asia',          '🇵🇰'),
    ('BD', 'Bangladesh',       'Asia',          '🇧🇩'),
    ('NP', 'Nepal',            'Asia',          '🇳🇵'),
    ('LK', 'Sri Lanka',        'Asia',          '🇱🇰'),
    ('IR', 'Iran',             'Asia',          '🇮🇷'),
    ('IQ', 'Iraq',             'Asia',          '🇮🇶'),
    ('IL', 'Israel',           'Asia',          '🇮🇱'),
    ('SA', 'Saudi Arabia',     'Asia',          '🇸🇦'),
    ('AE', 'UAE',              'Asia',          '🇦🇪'),
    ('QA', 'Qatar',            'Asia',          '🇶🇦'),
    ('KW', 'Kuwait',           'Asia',          '🇰🇼'),

    -- Africa
    ('EG', 'Egypt',            'Africa',        '🇪🇬'),
    ('MA', 'Morocco',          'Africa',        '🇲🇦'),
    ('DZ', 'Algeria',          'Africa',        '🇩🇿'),
    ('TN', 'Tunisia',          'Africa',        '🇹🇳'),
    ('LY', 'Libya',            'Africa',        '🇱🇾'),
    ('NG', 'Nigeria',          'Africa',        '🇳🇬'),
    ('GH', 'Ghana',            'Africa',        '🇬🇭'),
    ('CI', 'Ivory Coast',      'Africa',        '🇨🇮'),
    ('SN', 'Senegal',          'Africa',        '🇸🇳'),
    ('KE', 'Kenya',            'Africa',        '🇰🇪'),
    ('TZ', 'Tanzania',         'Africa',        '🇹🇿'),
    ('UG', 'Uganda',           'Africa',        '🇺🇬'),
    ('ET', 'Ethiopia',         'Africa',        '🇪🇹'),
    ('ZA', 'South Africa',     'Africa',        '🇿🇦'),
    ('ZW', 'Zimbabwe',         'Africa',        '🇿🇼'),

    -- Oceania
    ('AU', 'Australia',        'Oceania',       '🇦🇺'),
    ('NZ', 'New Zealand',      'Oceania',       '🇳🇿'),
    ('FJ', 'Fiji',             'Oceania',       '🇫🇯'),
    ('PG', 'Papua New Guinea', 'Oceania',       '🇵🇬'),
    ('WS', 'Samoa',            'Oceania',       '🇼🇸');