INSERT INTO country (id, name, continent, flag_emoji) VALUES
    ('CZ', 'Czech Republic',   'Europe',        '🇨🇿'),
    ('SK', 'Slovakia',         'Europe',        '🇸🇰'),
    ('AT', 'Austria',          'Europe',        '🇦🇹'),
    ('DE', 'Germany',          'Europe',        '🇩🇪'),
    ('FR', 'France',           'Europe',        '🇫🇷'),
    ('IT', 'Italy',            'Europe',        '🇮🇹'),
    ('ES', 'Spain',            'Europe',        '🇪🇸'),
    ('PT', 'Portugal',         'Europe',        '🇵🇹'),
    ('NL', 'Netherlands',      'Europe',        '🇳🇱'),
    ('BE', 'Belgium',          'Europe',        '🇧🇪'),
    ('CH', 'Switzerland',      'Europe',        '🇨🇭'),
    ('PL', 'Poland',           'Europe',        '🇵🇱'),
    ('HR', 'Croatia',          'Europe',        '🇭🇷'),
    ('GR', 'Greece',           'Europe',        '🇬🇷'),
    ('GB', 'United Kingdom',   'Europe',        '🇬🇧'),
    ('NO', 'Norway',           'Europe',        '🇳🇴'),
    ('SE', 'Sweden',           'Europe',        '🇸🇪'),
    ('IS', 'Iceland',          'Europe',        '🇮🇸'),
    ('US', 'United States',    'North America', '🇺🇸'),
    ('CA', 'Canada',           'North America', '🇨🇦'),
    ('MX', 'Mexico',           'North America', '🇲🇽'),
    ('BR', 'Brazil',           'South America', '🇧🇷'),
    ('AR', 'Argentina',        'South America', '🇦🇷'),
    ('CO', 'Colombia',         'South America', '🇨🇴'),
    ('PE', 'Peru',             'South America', '🇵🇪'),
    ('JP', 'Japan',            'Asia',          '🇯🇵'),
    ('CN', 'China',            'Asia',          '🇨🇳'),
    ('TH', 'Thailand',         'Asia',          '🇹🇭'),
    ('VN', 'Vietnam',          'Asia',          '🇻🇳'),
    ('ID', 'Indonesia',        'Asia',          '🇮🇩'),
    ('IN', 'India',            'Asia',          '🇮🇳'),
    ('NP', 'Nepal',            'Asia',          '🇳🇵'),
    ('TR', 'Turkey',           'Asia',          '🇹🇷'),
    ('AE', 'UAE',              'Asia',          '🇦🇪'),
    ('EG', 'Egypt',            'Africa',        '🇪🇬'),
    ('MA', 'Morocco',          'Africa',        '🇲🇦'),
    ('ZA', 'South Africa',     'Africa',        '🇿🇦'),
    ('KE', 'Kenya',            'Africa',        '🇰🇪'),
    ('TZ', 'Tanzania',         'Africa',        '🇹🇿'),
    ('AU', 'Australia',        'Oceania',       '🇦🇺'),
    ('NZ', 'New Zealand',      'Oceania',       '🇳🇿');